/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package casino;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author jakec
 */
public class Login extends javax.swing.JFrame {

    private int LoginSwitch = 0;
    private int RegisterSwitch = 0;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        UserInput = new javax.swing.JTextField();
        PassInput = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserRegisterInput = new javax.swing.JTextField();
        RegisterPassInput = new javax.swing.JPasswordField();
        LoginAccount = new javax.swing.JButton();
        CreateAccount = new javax.swing.JButton();
        InvalidRegister = new javax.swing.JLabel();
        InvalidLogin = new javax.swing.JLabel();
        Info5 = new javax.swing.JLabel();
        Info3 = new javax.swing.JLabel();
        Info2 = new javax.swing.JLabel();
        Info4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 70, 126, 39);

        jButton2.setText("Register");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(360, 70, 132, 39);
        getContentPane().add(UserInput);
        UserInput.setBounds(35, 148, 157, 33);
        getContentPane().add(PassInput);
        PassInput.setBounds(35, 217, 157, 34);

        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(240, 220, 80, 33);

        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(240, 150, 70, 33);
        getContentPane().add(UserRegisterInput);
        UserRegisterInput.setBounds(343, 148, 160, 33);
        getContentPane().add(RegisterPassInput);
        RegisterPassInput.setBounds(343, 214, 160, 37);

        LoginAccount.setText("Login to Account");
        LoginAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginAccountActionPerformed(evt);
            }
        });
        getContentPane().add(LoginAccount);
        LoginAccount.setBounds(50, 270, 120, 23);

        CreateAccount.setText("Create Account");
        CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountActionPerformed(evt);
            }
        });
        getContentPane().add(CreateAccount);
        CreateAccount.setBounds(360, 270, 120, 23);

        InvalidRegister.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        InvalidRegister.setForeground(new java.awt.Color(255, 0, 0));
        InvalidRegister.setText("Invalid Details");
        getContentPane().add(InvalidRegister);
        InvalidRegister.setBounds(360, 310, 124, 40);

        InvalidLogin.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        InvalidLogin.setForeground(new java.awt.Color(255, 0, 0));
        InvalidLogin.setText("Invalid Details");
        getContentPane().add(InvalidLogin);
        InvalidLogin.setBounds(50, 310, 124, 40);

        Info5.setForeground(new java.awt.Color(255, 0, 0));
        Info5.setText("• Password must have 1+ numbers");
        getContentPane().add(Info5);
        Info5.setBounds(320, 410, 250, 20);

        Info3.setForeground(new java.awt.Color(255, 0, 0));
        Info3.setText("• Password must have 1+ Lowercase characters");
        getContentPane().add(Info3);
        Info3.setBounds(290, 390, 390, 20);

        Info2.setForeground(new java.awt.Color(255, 0, 0));
        Info2.setText("• Password must have 1+ Uppercase characters");
        getContentPane().add(Info2);
        Info2.setBounds(290, 370, 350, 20);

        Info4.setForeground(new java.awt.Color(255, 0, 0));
        Info4.setText("• Password must be 8+ characters");
        getContentPane().add(Info4);
        Info4.setBounds(330, 350, 250, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int r = LoginSwitch % 2;
        if (r == 0) {
            UserInput.setVisible(true);
            PassInput.setVisible(true);
            LoginAccount.setVisible(true);
        } else if (r > 0) {
            UserInput.setVisible(false);
            PassInput.setVisible(false);
            LoginAccount.setVisible(false);
        }
        LoginSwitch++;
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int r = RegisterSwitch % 2;
        if (r == 0) {
            RegisterPassInput.setVisible(true);
            UserRegisterInput.setVisible(true);
            CreateAccount.setVisible(true);
        } else if (r > 0) {
            UserRegisterInput.setVisible(false);
            RegisterPassInput.setVisible(false);
            CreateAccount.setVisible(false);
        }
        RegisterSwitch++;
    }//GEN-LAST:event_jButton2ActionPerformed

    public String fulldir;
    public static int Currency;
    public static String loginName;
    private void LoginAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginAccountActionPerformed

        try {
            Connection connect = DriverManager.getConnection("jdbc:derby://localhost:1527/PlayersDatabase", "jake", "rose");
            Statement stmt = connect.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE); //Allows you to scroll through the list of records, and to Update the table.

            String sql = "SELECT * FROM app.TBL_PLAYERS";
            ResultSet Results = stmt.executeQuery(sql);

            while (Results.next()) {
                String username = Results.getString("PLAYERNAME");
                String password = Results.getString("PLAYERPASSWORD");
                if ((UserInput.getText().equals("Admin")) && (PassInput.getText().equals("AdminPassword"))) {
                    try {
                        sql = "SELECT * FROM app.TBL_PLAYERS";
                        Results = stmt.executeQuery(sql); //This will execute the SQL statement from the line above. A result set is a list of records.

                        while (Results.next()) {
                            username = Results.getString("PLAYERNAME");
                            password = Results.getString("PLAYERPASSWORD");
                            Currency = Results.getInt("PLAYERCURRENCY");
                            System.out.println("Username: " + username + " Password: " + password + " Currency: " + Currency);
                        }

                    } catch (Exception e) {
                        System.out.println(e);
                    }
                    
                } else if ((UserInput.getText().equals(username)) && (PassInput.getText().equals(password))) {
                    Currency = Results.getInt("PLAYERCURRENCY");
                    loginName = UserInput.getText();
                    dispose();
                    MainMenu LoadMainMenu = new MainMenu();
                    LoadMainMenu.setSize(700, 550);
                    LoadMainMenu.setVisible(true);
                    MainMenu.Chips.setText(Integer.toString(Currency));
                } else {
                    InvalidLogin.setVisible(true);
                }
            }

            Results.close();
            connect.close();
            stmt.close();

        } catch (Exception e) {
            System.out.println("Error: " + e);
        }

    }//GEN-LAST:event_LoginAccountActionPerformed

    private void CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAccountActionPerformed

        String CreateName = UserRegisterInput.getText(); //Sets the users imput from the text box and assigns it to the String variable
        String CreatePass = RegisterPassInput.getText(); //Sets the users imput from the password text box and assigns it to the other String variable
        fulldir = System.getProperty("user.dir") + "\\Players.txt"; //global variable, fulldir, 

        Pattern RegularExpression = Pattern.compile("^(?=.*[0-9])(?=.*[a-z]).{4,32}$"); /*Defines the valid strings that can be used in the password.
                                                                                        For this regular expression, there must be, atleast 8 characters, 1+ Uppercase and Lowercase, and 1+ number.*/
        Matcher UsesCorrectFormat = RegularExpression.matcher(CreatePass); //This will compare the userinput "CreatePass" with the regular expression

        if (UsesCorrectFormat.matches()) { //if the matcher is valid and is matching the regular expression, it will set the statement to True.
            try {

                Connection connect = DriverManager.getConnection("jdbc:derby://localhost:1527/PlayersDatabase", "jake", "rose"); //This will connect to the database
                Statement stmt = connect.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE); //Allows you to scroll through the list of records, and to Update the table.

                String sql = "INSERT INTO app.TBL_PLAYERS VALUES ('" + UserRegisterInput.getText() + "','" + RegisterPassInput.getText() + "',1000)"; //This is the SQL statement to be executed on the database. This will append the username and the password entered, with the integer "1000" to the end. 
                stmt.execute(sql); //Executes the SQL
                
                connect.close(); //These lines are for housekeeping, and closing all the opened objects
                stmt.close();

            } catch (Exception e) {
                System.out.println("Error: " + e); 
            }
            Currency = 1000; 
            dispose();   //Creating a new window
            MainMenu LoadMainMenu = new MainMenu();
            LoadMainMenu.setSize(700, 550);
            LoadMainMenu.setVisible(true);
            LoadMainMenu.setLocationRelativeTo(null); // Opens the window in the centre of the screen.
            MainMenu.Chips.setText(Integer.toString(1000)); 
        } else {
            InvalidRegister.setVisible(true);  
            Info5.setVisible(true);
            Info2.setVisible(true);
            Info3.setVisible(true);
            Info4.setVisible(true);
        }

    }//GEN-LAST:event_CreateAccountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton CreateAccount;
    public static javax.swing.JLabel Info2;
    public static javax.swing.JLabel Info3;
    public static javax.swing.JLabel Info4;
    public static javax.swing.JLabel Info5;
    public static javax.swing.JLabel InvalidLogin;
    public static javax.swing.JLabel InvalidRegister;
    public static javax.swing.JButton LoginAccount;
    public static javax.swing.JPasswordField PassInput;
    public static javax.swing.JPasswordField RegisterPassInput;
    public static javax.swing.JTextField UserInput;
    public static javax.swing.JTextField UserRegisterInput;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
